/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardBody: typeof import('bootstrap-vue-next/components/BCard')['BCardBody']
    BCardImg: typeof import('bootstrap-vue-next/components/BCard')['BCardImg']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    ContactSection: typeof import('./src/components/ContactSection.vue')['default']
    CoverSection: typeof import('./src/components/CoverSection.vue')['default']
    CustomCard: typeof import('./src/components/CustomCard.vue')['default']
    CustomMenu: typeof import('./src/components/CustomMenu.vue')['default']
    ExperienceAndProjectsSection: typeof import('./src/components/ExperienceAndProjectsSection.vue')['default']
    LoadingScreen: typeof import('./src/components/LoadingScreen.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
